### ISSUE TITLE
zrep tags, for multiple destinations, are problematic

### ISSUE THREAD

**Issue by ksalman** [olevole/zrep#3]
Since zrep now supports tags for multiple destinations, I have been taking advantage of this and syncing source with two destinations. But zrep sends all intermediary snapshots, using the -I opiton, https://github.com/olevole/zrep/blob/master/zrep#L953. The snaphsots created on the source look like this

```
NAME                                     USED  AVAIL  REFER  MOUNTPOINT
datapool/ops-spool@zrep-brigade_0000c0      0      -   773M  -
datapool/ops-spool@zrep_0001e1              0      -   773M  -
```

Next when I do another zrep with zrep-brigade tag, it sends both zrep_0001e1 and zrep-brigade_0000c1, which is not what we want.

This would not be a big deal except that when it comes time to expiring old snapshots, say, for tag zrep-brigade, it only expires zrep-brigade snapshots, logically. And all the other zrep_xxx snapshots stick around, and keep accumulating. You could remove the -I option when doing a zfs send and I don't think removing it would affect zrep operation. I removed it in my local copy, and testing it, but wanted to create an issue if other folks can see why zrep is sending and accumulating other tags, when doing multi-destination syncs.

**Comment by olevole** [comment]
It makes sense to try the new version of zrep from original author: http://www.bolthole.com/solaris/zrep/
Because this  zrep  is just adapted/rewritten from ksh-specific code to POSIX sh(1) by me and this version already obsolete.

**Comment by ksalman** [comment]
Sorry, I didn't realize this was not the original project.
